### ISSUE TITLE
Validation rule to prevent `any` version

### ISSUE THREAD

**Issue by matthewnitschke-wk** [Workiva/dependency_validator#134]
Pubspec.yaml files technically support `any` as a possible version:

```yaml
some_dep: any

some_dep2:

some_dep3:
  hosted:
    name: some_dep3
    url: https://some_url.org
```

While this is valid for development use cases, this _will_ fail during publish to pub, and would be nice if dependency_validator could catch

Consider this as an opt-in functionality
