### ISSUE TITLE
[Request] Possible to user a specific comment to exclude certain packages?

### ISSUE THREAD

**Issue by MostHated** [Workiva/dependency_validator#63]
Hey there,
    I use this quite often when I am testing out a bunch of different packages and seeing what I like best as sometimes I will remove something from code but forget to remove it from the pubspec. There are a decent number of them, though, that need to stay in there for various reasons, but end up showing up on the list and it can be a pain to try and add them as an ignore each time.

    Is it possible that, perhaps, something like this could be used?

Example:
```yaml
  cross_local_storage: ^1.1.1
  draggable_scrollbar: ^0.0.4
  event: ^1.1.4
  event_bus: ^1.1.1 #skip
  eventsubscriber: ^1.2.0
  file_picker: ^1.11.0+2 #skip
  flutter_markdown: ^0.4.1
  get_it: ^4.0.2
```

Then the ones that have #skip (or whatever would be best to use) do not get included in the output after a check? If not that, then what might also work is perhaps something like:

```
// dep_ignore.json
{
  event_bus: ^1.1.1
  eventsubscriber: ^1.2.0
  file_picker: ^1.11.0+2
}
```
```
> dependency_validator --skip-file=dep_ignore.json
```

Really, anything would help, as I am making a desktop app and I have a fairly large number of them that would end up on the list. So being able to do at least something with the ones I know I will always skip would be quite nice.

Thanks,
-MH

**Comment by evanweible-wf** [comment]
Hi @MostHated! Totally agree, we've actually got an integration branch in progress for a 2.0.0 release that switches from using command-line args to using static configuration in the `pubspec.yaml`. It will look like this:

```yaml
# pubspec.yaml
name: example

dependencies:
  event_bus: ^1.1.1

dependency_validator:
  ignore:
    - event_bus  # could add a comment here explaining why it is ignored
```

We've got one more main feature to add (#62) and then we just need to get the docs updated before releasing it.
